# Generated by Django 6.0.6 on 2026-06-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksboardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=1000)),
                ('task_description', models.TextField()),
                ('task_due_date', models.DateTimeField(auto_now=True)),
                ('task_priority', models.CharField(default='Medium', max_length=100)),
                ('task_created_date', models.DateTimeField(auto_now_add=True)),
                ('task_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tasksboard_details',
            },
        ),
    ]
