# Generated by Django 6.0.6 on 2026-06-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard_endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasksboarddetails',
            table=None,
        ),
    ]
