# Generated by Django 6.0.6 on 2026-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard_endpoint', '0002_alter_tasksboarddetails_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksboarddetails',
            name='task_due_date',
            field=models.DateTimeField(),
        ),
    ]
