# Generated by Django 6.0.6 on 2026-06-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard_endpoint', '0003_alter_tasksboarddetails_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksboarddetails',
            name='task_due_date',
            field=models.DateField(),
        ),
    ]
