# Generated by Django 6.0.6 on 2026-06-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard_endpoint', '0004_alter_tasksboarddetails_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksboarddetails',
            name='task_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
